<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-17 19:46:44',
                'updated_at' => '2020-03-17 19:46:44',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-17 19:46:44',
                'updated_at' => '2020-03-17 19:46:44',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-17 19:46:44',
                'updated_at' => '2020-03-17 19:46:44',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-17 19:46:50',
                'updated_at' => '2020-11-05 22:59:18',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-17 19:46:51',
                'updated_at' => '2020-03-17 19:46:51',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-17 19:46:52',
                'updated_at' => '2020-03-17 19:46:52',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'orders',
                'slug' => 'orders',
                'display_name_singular' => 'Order',
                'display_name_plural' => 'Orders',
                'icon' => 'voyager-buy',
                'model_name' => 'App\\Order',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-17 21:00:55',
                'updated_at' => '2020-03-18 17:44:50',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'shops',
                'slug' => 'shops',
                'display_name_singular' => 'Shop',
                'display_name_plural' => 'Shops',
                'icon' => 'voyager-shop',
                'model_name' => 'App\\Shop',
                'policy_name' => '\\App\\Policies\\ShopPolicy',
                'controller' => 'App\\Http\\Controllers\\Admin\\ShopController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-23 06:28:19',
                'updated_at' => '2020-03-23 23:31:33',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-bag',
                'model_name' => 'App\\Product',
                'policy_name' => 'App\\Policies\\ProductPolicy',
                'controller' => 'App\\Http\\Controllers\\Admin\\ProductController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-23 06:28:50',
                'updated_at' => '2021-02-14 16:34:44',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'sub_order_items',
                'slug' => 'sub-order-items',
                'display_name_singular' => 'Sub Order Item',
                'display_name_plural' => 'Sub Order Items',
                'icon' => NULL,
                'model_name' => 'App\\SubOrderItem',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-05 22:02:09',
                'updated_at' => '2020-11-05 22:02:09',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'sub_orders',
                'slug' => 'sub-orders',
                'display_name_singular' => 'Sub Order',
                'display_name_plural' => 'Sub Orders',
                'icon' => NULL,
                'model_name' => 'App\\SubOrder',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-05 22:03:54',
                'updated_at' => '2020-11-05 22:03:54',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'transactions',
                'slug' => 'transactions',
                'display_name_singular' => 'Transaction',
                'display_name_plural' => 'Transactions',
                'icon' => NULL,
                'model_name' => 'App\\Transaction',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-05 22:29:19',
                'updated_at' => '2020-11-05 22:29:19',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'attributes',
                'slug' => 'attributes',
                'display_name_singular' => 'Attribute',
                'display_name_plural' => 'Attributes',
                'icon' => NULL,
                'model_name' => 'App\\Attribute',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-02-14 16:21:03',
                'updated_at' => '2021-02-14 16:40:42',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'attribute_values',
                'slug' => 'attribute-values',
                'display_name_singular' => 'Attribute Value',
                'display_name_plural' => 'Attribute Values',
                'icon' => 'voyager-list',
                'model_name' => 'App\\AttributeValue',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-02-14 16:21:57',
                'updated_at' => '2021-02-14 16:39:58',
            ),
        ));
        
        
    }
}